services:
  web:
    build: .
    container_name: mywebsite
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot

volumes:
  certbot_www: